name       : opal
version    : 3.10.11
release    : 7
source     :
    - https://netix.dl.sourceforge.net/project/opalvoip/v3.10%20Luyten/Stable%2011/opal-3.10.11.tar.bz2 : f38e7969e88a28dd9a10a6051315aceecde79d0bbd1a35676868dc5787aed706
license    : MPL-1.0
component  : programming
summary    : Open Phone Abstraction Library (OPAL)
description: |
    Open Phone Abstraction Library (OPAL) is a C++ multi-platform, multi-protocol library for Fax, Video & Voice over IP and other networks
libsplit   : no
builddeps  :
    - pkgconfig(celt)
    - pkgconfig(ogg)
    - pkgconfig(ptlib)
    - pkgconfig(speex)
    - pkgconfig(x264)
setup      : |
    %apply_patches
    sed -e '/<< mime.PrintContents/ s/mime/(const std::string\&)&/' -i src/im/msrp.cxx
    %configure --disable-static --disable-libavcodec
build      : |
    %make
install    : |
    %make_install
