name       : opal
version    : 3.10.10
release    : 2
source     :
    - http://ftp.gnome.org/pub/gnome/sources/opal/3.10/opal-3.10.10.tar.xz : f208985003461b2743575eccac13ad890b3e5baac35b68ddef17162460aff864
license    : MPL-1.0
component  : programming
summary    : Open Phone Abstraction Library (OPAL)
description: |
    Open Phone Abstraction Library (OPAL) is a C++ multi-platform, multi-protocol library for Fax, Video & Voice over IP and other networks
libsplit : no
builddeps  :
    - pkgconfig(celt)
    - pkgconfig(libavcodec)
    - pkgconfig(ogg)
    - pkgconfig(ptlib)
    - pkgconfig(speex)
    - pkgconfig(x264)
setup      : |
    %patch -p1 < $pkgfiles/opal-ffmpeg.patch
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
